trigger:
- master
- rel/*

variables: 
  BuildConfiguration: Release
  
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: build/setversion.csproj
    arguments: -c $(BuildConfiguration)   
  displayName: Set Version
  condition: eq(variables['system.pullrequest.isfork'], false)
    
- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: Refit/Refit.csproj
    arguments: -c $(BuildConfiguration)   
  displayName: Build
  
- task: DotNetCoreCLI@2
  inputs:
    command: pack
    projects: Refit/Refit.csproj
    arguments: -c $(BuildConfiguration) -o .\artifacts
  displayName: Pack

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: Refit.Tests/Refit.Tests.csproj
    arguments: -c $(BuildConfiguration) 
  displayName: Run Tests

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: .\artifacts
    artifactType: container
    artifactName: Packages
  condition: eq(variables['system.pullrequest.isfork'], false)
