image: Visual Studio 2017
configuration: Release  
install: 
  - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.1.0/NuGet.exe
     
init:
  - git config --global core.autocrlf input

skip_branch_with_pr: true
       
before_build:
  - cmd: msbuild /t:restore Refit.sln
  
build:
  verbosity: normal
  parallel: true
  project: Refit.sln
  
after_build:
  - ps: |
      $vers = & $env:UserProfile\.nuget\packages\nerdbank.gitversioning\2.0.4-beta\tools\Get-Version.ps1
      $env:NuGetPackageVersion = $vers.NuGetPackageVersion      
  - cmd: nuget pack Refit\Refit.nuspec -version "%NuGetPackageVersion%" -prop "target=%CONFIGURATION%" -NoPackageAnalysis
  - cmd: appveyor PushArtifact "Refit.%NuGetPackageVersion%.nupkg"  
  
deploy:
  provider: NuGet
  server: https://www.myget.org/F/refit/api/v2/package
  on:
    branch: master  
  api_key:
    secure: bmqlJK8a5HYiUXOT99HXT1j7JiM5+fpR4kHhxIC30oaaEXbv94f0fKdiKlU1QC/l
  artifact: /.*\.nupkg/
